### ISSUE TITLE
Does epple2 still depend on Apple ][ Disk Tools? 

### ISSUE THREAD

**Issue by lifepillar** [cmosher01/Epple-II#1]
According to the [Readme](https://github.com/cmosher01/Apple-II-Disk-Tools), epple2 does not require Apple ][ Disk Tools any longer. But if I remove the dependency from Apple ][ Disk Tools in the [Homebrew formula](https://github.com/lifepillar/homebrew-appleii/blob/master/Formula/epple2.rb) I maintain, I get an error complaining about `a2catalog` not being found. With such dependency, epple2 builds fine.

What are the correct dependencies, currently?

**Comment by cmosher01** [comment]
@lifepillar, sorry for not seeing this sooner. Epple 2 does not, nor has ever, depended on a2catalog. But https://github.com/cmosher01/Apple-II-Source did at one point in the past. In your Homebrew formula, can you build the latest from master branch of Apple-II-Source instead of from the old 1.0 source tarball?

**Comment by lifepillar** [comment]
Thanks, using the current master I can build without a2catalog. May you tag a point release of Apple-II-Source, so I can link to that rather than HEAD?

**Comment by cmosher01** [comment]
Release `1.1` created. Please confirm working or not. Thank you, @lifepillar .

**Comment by cmosher01** [comment]
Now there's a [v1.1.2](https://github.com/cmosher01/Apple-II-Source/releases/tag/v1.1.2) official build (via Travis).

**Comment by lifepillar** [comment]
Thanks, that builds fine! I have [updated the formula](https://github.com/lifepillar/homebrew-appleii/commit/26b3f657b368961d43057d899f4dd20e4e7bed38) to reflect your updates.
