### ISSUE TITLE
How to install into a custom location?

### ISSUE THREAD

**Issue by lifepillar** [cmosher01/Epple-II#13]
Up to v1.0.6, I was able to specify a custom install location with `./configure --prefix=...`. Now, it seems that Epple-II has switched to Cmake. Is it possible to have the binary and the configuration files installed into a custom location? Or should they be copied manually?

**Comment by cmosher01** [comment]
This is a work in progress. When finished, there will be several different installation packages to choose from for each platform. You will be able to install the software in any location, and it will "just work".

In the meantime, you can use cmake to configure an installation prefix, similar to what ./configure does. Look for help on the <pre>--install-prefix</pre> option to cmake.
