### ISSUE TITLE
macOS installer installs libSDL in the wrong place and it has the wrong install name

### ISSUE THREAD

**Issue by ryandesign** [cmosher01/Epple-II#14]
I used the epple 1.1.1 pkg for macOS. It installed /usr/local/bin/epple2 but it fails to run:

```
% /usr/local/bin/epple2 
dyld[59677]: Library not loaded: '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib'
  Referenced from: '/usr/local/bin/epple2'
  Reason: tried: '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file)
zsh: abort      /usr/local/bin/epple2
```

The installer did not install /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (and if it did, that would be a weird place to install it). Instead, it installed /usr/local/bin/libSDL2.dylib (which is a weird place to install it).

I can correct the problems by running:

```
% sudo mv /usr/local/bin/libSDL2.dylib /usr/local/lib/libSDL2-2.0.0.dylib
% sudo install_name_tool -id /usr/local/lib/libSDL2-2.0.0.dylib /usr/local/lib/libSDL2-2.0.0.dylib
% sudo install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib /usr/local/lib/libSDL2-2.0.0.dylib /usr/local/bin/epple2
```

but I shouldn't have to do that.

Finally, /usr/local isn't a good place to install your software. It may conflict with other software already installed there. Even if it does not, libraries installed in /usr/local/lib are automatically detected by compilers, which may adversely affect users trying to compile other software. Please pick a unique prefix, such as /opt/epple. Or, even better, use a macOS application bundle and locate your extra files within the application bundle, in Library/Preferences, or in Library/Application Support.

**Comment by cmosher01** [comment]
This will be fixed in version 2.0. Installation will be rewritten using CMake.

**Comment by cmosher01** [comment]
Clarification regarding comment "`/usr/local` isn't a good place to install your software": in fact, `/usr/local` is the default installation location per standard GNU Autotools: https://www.gnu.org/software/autoconf/manual/autoconf-2.72/html_node/Installation-Names.html . Distribution packagers can use `--prefix` to change the installation prefix as desired.

**Comment by ryandesign** [comment]
> Clarification regarding comment "`/usr/local` isn't a good place to install your software": in fact, `/usr/local` is the default installation location per standard GNU Autotools: https://www.gnu.org/software/autoconf/manual/autoconf-2.72/html_node/Installation-Names.html .

Right, it is. That doesn't make it a good place to install your software.

> Distribution packagers can use `--prefix` to change the installation prefix as desired.

This bug report is about the pre-compiled macOS binary, not building from source.

**Comment by cmosher01** [comment]
The prebuilt binary packages are only a convenience, and are not supported.
