### ISSUE TITLE
Rendering on macOS: issue with retina display?

### ISSUE THREAD

**Issue by lifepillar** [cmosher01/Epple-II#2]
epple2's screen is next to unreadable, at least on macOS:

<img width="752" alt="Screenshot 2019-04-12 at 19 22 38" src="https://user-images.githubusercontent.com/1193314/56054983-a2b84000-5d58-11e9-8664-3e30b211f88f.png">

In the past I didn't have such issue: perhaps it's because I use a different computer with retina display. In fullscreen mode things are only slightly better—the text is still very small.

**Comment by cmosher01** [comment]
I'm planning a v2.0.0 version using Qt Widgets, which should resolve any readability issues.

**Comment by cmosher01** [comment]
Also, you can try F3 for full-screen mode and see if looks any better.
