### ISSUE TITLE
osx v1.0.5 release

### ISSUE THREAD

**Issue by mbrethen** [cmosher01/Epple-II#5]
The v1.0.5 release for osx is only 175k whereas the linux and windows files are >1mb. Am I missing something?

**Comment by chris-mosher** [comment]
It's not built with debug symbols (i.e., it's stripped).

**Comment by cmosher01** [comment]
I just released version 1.0.6 with a new PKG file for Mac that includes the config files and demo ROM. It should make a better out-of-the-box experience. It's still small, at 173K. If you run into any trouble, please let me know. Thank you.
