### ISSUE TITLE
Info about cassettein

### ISSUE THREAD

**Issue by audetto** [cmosher01/Epple-II#6]
Hi

I saw your code for the TAPEIN feature (https://github.com/cmosher01/Epple-II/blob/55a43d19f014e8e5c55142d9fd8a6172b80ec752/src/cassettein.cpp#L114)

I was trying to copy the code and port it to AppleWin.

I tried alternative ways to set the bit (e.g. if the wave is above or below a threshold).

In your experience, how important is to get this exact? I suspect a real hardware is so noisy that all these details are not so important. How did you test your code? I use http://asciiexpress.net/gameserver/ , but I only seem to get the Monitor code working.

**Comment by cmosher01** [comment]
It's the duration of the cycle that matters, not the strength. The most accurate way I could come up with is what's documented in that source file... looking for the change in slope between positive/negative to indicate the beginning of a cycle. But it's still hit or miss with analog data. I also did some work on processing cassette input with [Apple-II-Cassette-Recover](https://github.com/cmosher01/Apple-II-Cassette-Recover/blob/master/a2cassre.cpp), which tries to build a clean wav file. It looks at the input cycle lengths and decides which of the known expected durations it's closest to. It's still not perfect. I ran many tests of real wav files from cassettes, and some worked, but some didn't.

**Comment by audetto** [comment]
Eventually I figured out how to process all formats from https://asciiexpress.net/ but I admit my code will probably struggle with a real analogue input.

**Comment by cmosher01** [comment]
There's a large collection of analog captures at [Brutal Deluxe](https://www.brutaldeluxe.fr/projects/cassettes/). I remember trying many of those, and some worked in Epple II, but some didn't. I'd be interested if your code could handle these. Where is your code? In AppleWin?

**Comment by audetto** [comment]
AppleWin on Linux.

https://github.com/audetto/AppleWin/blob/master/source/linux/tape.cpp#L37-L57

Will try your link
