### ISSUE TITLE
Investigate making Windows .msix installer, and signing the package

### ISSUE THREAD

**Issue by cmosher01** [cmosher01/Epple-II#9]

**Comment by xotmatrix** [comment]
I'm not a fan of installers because I keep 700 GB of emulation stuff on a dedicated drive. If you go this way, please consider a portable version.

**Comment by chris-mosher** [comment]
Does the current ZIP file meet your needs? You can put it anywhere and edit the config file appropriately. I wasn't planning on eliminating that, only in providing an additional installation package. Were you specifically looking for a package in this format: https://portableapps.com/development/portableapps.com_format ?

**Comment by xotmatrix** [comment]
I don't need any special package format. A plain ZIP file is good as long as the config file is set up to look for library/data files in a relative directory. 

The config files in the current 1.1.0 release all point to `C:\Program Files (x86)\` which is not ideal for a few reasons:
1. That may not be a valid or desired path for applications.
2. It is not expected to use that path without an installer nor permitted without admin privileges.
3. Epple-II is a 64-bit application so it doesn't belong in that path anyway; this is what `\Program Files\` is for.
4. It is not expected for the application or user to add data files to the standard Windows installation paths (eg. the various `.a65` files); `\ProgramData\` is what an application should use for data files that are subject to change, if the user does specify some other location. `%APPDATA%` or `%LOCALAPPDATA%` are other common locations application data, though maybe more difficult for the user to find.

I can't claim what the "best practices" are for Windows application development but I believe the above points are valid and correct.

A portable version from a ZIP file that can go anywhere without any fuss or needing to look for files outside of its base directory is just a nicer solution for me. With one exception, every emulator I use works this way.

**Comment by cmosher01** [comment]
I already know about the config file path problems, but that's a separate issue and there's already a ticket for that: #11 

I'll need to do more research on the standard practices for Windows.

**Comment by cmosher01** [comment]
Note: the `.a65` files are not data, they are ROM code, and therefore belong with the program executable.

**Comment by xotmatrix** [comment]
Perhaps they belong with the application but the package doesn't include them. It is not correct to expect the user to add files to a standard Windows installation directory and Windows will resist the effort. That is a protected area that requires elevated permissions to modify. A normal user can only read and execute files there. An application could copy files into that directory but only when granted elevated permissions that a normal user is unable to grant. There are more permissible directories for this kind of thing, such as `%ProgramData%` or `%LocalAppData%` for application-facing files, and for files that the user is expected to find, create, and modify, `%UserProfile%`.

Or one could simply allow the user to pick an arbitrary path, which in my experience is how most emulators handle ROM files. In my view, a ROM file has no more business in the installation directory than a disk image.

**Comment by cmosher01** [comment]
@xotmatrix, can you explain what you mean by "the package doesn't include them"?

**Comment by cmosher01** [comment]
To clarify, the user can install any files (program, data, roms, configs, disk images) in any location. Nothing currently requires "Program Files" or any other specific location. The user can pick any arbitrary path for any file.

**Comment by xotmatrix** [comment]
> @xotmatrix, can you explain what you mean by "the package doesn't include them"?

Sometime after v1.0.5 you stopped including Apple's ROMs.

> To clarify, the user can install any files (program, data, roms, configs, disk images) in any location. Nothing currently requires "Program Files" or any other specific location. The user can pick any arbitrary path for any file.

Right now, but this issue is about Windows installers which do have constraints about where software can be installed and what can be accessed in those locations afterword. It looks like MSIX goes even further than MSI to prevent the user from accessing such locations. 

Under Windows 11 there may be some options but this is unclear. At the same time, it looks like MSIX apps themselves are normally not permitted to write to default installation directories and the default WindowsApps directories are hidden from users and admins alike.

**Comment by cmosher01** [comment]
MSIX, or any installer, won't affect the ability of Epple-II to run from any location and have it's config and other files in any location.

I don't remember if ROMs were included or not in previous releases, but the current release does have ROM files.

**Comment by cmosher01** [comment]
Regardless... CMake and CPack provide NSIS installer, and that's what I'll be using. Closing this issue.
